### ISSUE TITLE
I encountered some problems running the code

### ISSUE THREAD

**Issue by mqli0625** [git-disl/Fed-CDP#1]
The machine reported some errors while I was running the file FedCDP.py,
Traceback (most recent call last):
  File "C:\Users\LMQ\Desktop\Fed-CDP-main\Fed-CDP-main\FedCDP.py", line 145, in <module>
    client_set = pickle.load(open('./clients/' + str(total_client_num) + '_clients.pkl', 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: './clients/1000_clients.pkl'
Can you give me some help? Thank you!

**Comment by WenqiWei789** [comment]
> The machine reported some errors while I was running the file FedCDP.py, Traceback (most recent call last): File "C:\Users\LMQ\Desktop\Fed-CDP-main\Fed-CDP-main\FedCDP.py", line 145, in client_set = pickle.load(open('./clients/' + str(total_client_num) + '_clients.pkl', 'rb')) FileNotFoundError: [Errno 2] No such file or directory: './clients/1000_clients.pkl' Can you give me some help? Thank you!

Hi, I have updated the code. You may want to run create_FLdistribution.sh first to create a client distribution first(each client has two shards). Then the xxx_1000_clients.pkl would appear in the client folder and you can run the rest.

**Comment by mqli0625** [comment]
Thank you very much for your reply. File the xxx_1000_clients.pkl can be generated according to the steps you said, but there is another problem in the subsequent operation. I really hope you can spare some time to help look at it, thank you!
/MNIST_original\train-labels-idx1-ubyte
./MNIST_original\t10k-labels-idx1-ubyte
WARNING:tensorflow:Calling GradientTape.gradient on a persistent tape inside its context is significantly less efficient than calling it outside the context (it causes the gradient ops to be recorded on the tape, leading to increased CPU and memory usage). Only call GradientTape.gradient inside the context if you actually want to trace the gradient in order to compute higher order derivatives.
(100,)
l2: tf.Tensor(6.6356967533950435, shape=(), dtype=float64)
l2: tf.Tensor(54.560121932823826, shape=(), dtype=float64)
l2: tf.Tensor(50.743545833113146, shape=(), dtype=float64)
Traceback (most recent call last):
  File "C:\Users\LMQ\Desktop\Fed-CDP-main\Fed-CDP-main\FedCDP.py", line 387, in <module>
    logits_all = new_global_model(np.asarray(sorted_x_train)[:10000], 0)
  File "C:\Users\LMQ\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\engine\base_layer.py", line 1037, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "C:\Users\LMQ\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\engine\sequential.py", line 369, in call
    return super(Sequential, self).call(inputs, training=training, mask=mask)
  File "C:\Users\LMQ\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\engine\functional.py", line 414, in call
    return self._run_internal_graph(
  File "C:\Users\LMQ\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\engine\functional.py", line 559, in _run_internal_graph
    assert x_id in tensor_dict, 'Could not compute output ' + str(x)
AssertionError: Could not compute output KerasTensor(type_spec=TensorSpec(shape=(10000, 10), dtype=tf.float32, name=None), name='dense/Softmax:0', description="created by layer 'dense'")

**Comment by WenqiWei789** [comment]
> Thank you very much for your reply. File the xxx_1000_clients.pkl can be generated according to the steps you said, but there is another problem in the subsequent operation. I really hope you can spare some time to help look at it, thank you!
> /MNIST_original\train-labels-idx1-ubyte
> ./MNIST_original\t10k-labels-idx1-ubyte
> WARNING:tensorflow:Calling GradientTape.gradient on a persistent tape inside its context is significantly less efficient than calling it outside the context (it causes the gradient ops to be recorded on the tape, leading to increased CPU and memory usage). Only call GradientTape.gradient inside the context if you actually want to trace the gradient in order to compute higher order derivatives.
> (100,)
> l2: tf.Tensor(6.6356967533950435, shape=(), dtype=float64)
> l2: tf.Tensor(54.560121932823826, shape=(), dtype=float64)
> l2: tf.Tensor(50.743545833113146, shape=(), dtype=float64)
> Traceback (most recent call last):
> File "C:\Users\LMQ\Desktop\Fed-CDP-main\Fed-CDP-main\FedCDP.py", line 387, in 
> logits_all = new_global_model(np.asarray(sorted_x_train)[:10000], 0)
> File "C:\Users\LMQ\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\engine\base_layer.py", line 1037, in **call**
> outputs = call_fn(inputs, *args, **kwargs)
> File "C:\Users\LMQ\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\engine\sequential.py", line 369, in call
> return super(Sequential, self).call(inputs, training=training, mask=mask)
> File "C:\Users\LMQ\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\engine\functional.py", line 414, in call
> return self._run_internal_graph(
> File "C:\Users\LMQ\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\engine\functional.py", line 559, in _run_internal_graph
> assert x_id in tensor_dict, 'Could not compute output ' + str(x)
> AssertionError: Could not compute output KerasTensor(type_spec=TensorSpec(shape=(10000, 10), dtype=tf.float32, name=None), name='dense/Softmax:0', description="created by layer 'dense'")

Hi. I am not sure the exact cause for this but I doubt it is because of the dependencies and tensorflow version. Thereby, I created a environment.yml file with my current condo environment.
